## You should change each of the following fields
## to customize your blog

title: Welcome to my blog!
description: "Welcome to my journey as I work towards becoming a professional data analyst and scientist. This blog is where I share my insights, challenges, and discoveries along the way. Let’s learn and grow together!" 
author: Hongting (Ketherine) Wang
author_description: "I am Ketherine, an aspiring data scientist with a passion for uncovering insights from data. Currently pursuing my studies in Statistics with an emphasis in Data Science and a minor in Computer Science. I am enthusiastic about sharing what I learn---from SQL tips to data visualization techniques. Join me as I explore the fascinating world of data anlytics, one blog post at a time."

url: https://ketherinewang.github.io ## change this to https://yourusername.github.io
baseurl: /my-blog ## change this to the name of your blog repository
header_image: /assets/img/homepagebackground.webp ## change your header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github: KetherineWang
    twitter: 
    facebook: 
    email: hongtingwang718@gmail.com
    linkedin: www.linkedin.com/in/hongting-ketherine-wang
    youtube: 
    tumblr: 
    website: 



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

theme: minima
markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




